### ISSUE TITLE
Could you explain a bit more what the point is of the GraphQLInputObject?

### ISSUE THREAD

**Issue by Evertt** [nerdsupremacist/GraphZahl#16]
Not just for me here in this issue, but maybe it would be nice to explain it more in the readme.

Because when I read [this part of the readme](https://github.com/nerdsupremacist/GraphZahl#graphqlinputobject), I didn't immediately see the added value of using a `GraphQLInputObject` rather than just plain function arguments. And I still don't see it.

**Comment by nerdsupremacist** [comment]
tbh this is not a feature that is used very often in GraphQL in General. But it's part of the Type System so I included it.

Why you would use it? For example you want to make a set of two argument optional, but they should always appear together, then you could group them in an Input Object.

As here: 

```swift
enum Order: String, CaseIterable, GraphQLEnum {
    case ascending
    case descending
}

struct SortOptions: GraphQLInputType {
    let field: KeyPath<Result, Int>
    let order: Order
}

func search(term: String, sortOptions: SortOptions?) -> [Result] {
    ...
}
```

It means that you can give no options for sorting, and the values won't be sorted. But if you tell by what to sort, you have to also say if it's ascending or descending...

Like I said, it's not a widely used feature. But GitHub uses it very heavily. So I felt like this library would be incomplete without it
